// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwuKNeAs75ZMMfj_a_2ego0jFB89sGg1s',
    appId: '1:220783516120:web:616a56978301054024faad',
    messagingSenderId: '220783516120',
    projectId: 'geoguideapp-21d6e',
    authDomain: 'geoguideapp-21d6e.firebaseapp.com',
    databaseURL: 'https://geoguideapp-21d6e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geoguideapp-21d6e.firebasestorage.app',
    measurementId: 'G-8D1P0EQET7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClnVOvH1hqz1i-6ckTNYkPEEt0qFRHhik',
    appId: '1:220783516120:android:38836fd3d1edf7a024faad',
    messagingSenderId: '220783516120',
    projectId: 'geoguideapp-21d6e',
    storageBucket: 'geoguideapp-21d6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMkAYgzfbnjniL43GDaRyLZx_tGII-K0',
    appId: '1:220783516120:ios:ee98b4ec500224a524faad',
    messagingSenderId: '220783516120',
    projectId: 'geoguideapp-21d6e',
    storageBucket: 'geoguideapp-21d6e.firebasestorage.app',
    iosBundleId: 'com.example.geoguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMkAYgzfbnjniL43GDaRyLZx_tGII-K0',
    appId: '1:220783516120:ios:ee98b4ec500224a524faad',
    messagingSenderId: '220783516120',
    projectId: 'geoguideapp-21d6e',
    storageBucket: 'geoguideapp-21d6e.firebasestorage.app',
    iosBundleId: 'com.example.geoguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwuKNeAs75ZMMfj_a_2ego0jFB89sGg1s',
    appId: '1:220783516120:web:ea40aa300f92d1ae24faad',
    messagingSenderId: '220783516120',
    projectId: 'geoguideapp-21d6e',
    authDomain: 'geoguideapp-21d6e.firebaseapp.com',
    storageBucket: 'geoguideapp-21d6e.firebasestorage.app',
    measurementId: 'G-BXB4JBPD20',
  );
}